[package]
name = "fourcast"
version = "2.0.0"
authors = []

[addresses]
fourcast_addr = "_"

[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "testnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
